Allocate Material Above Nodes
oceanbase/oceanbase pull request #1437
Opened 2023-06-16 05:57 UTC by zhangyuqin1998

### Task Description

### Solution Description

### Passed Regressions

### Upgrade Compatibility

### Other Information

### Release Note

2023-06-16 06:08 UTC, zhangyuqin1998 commented on src/sql/code_generator/ob_static_engine_cg.cpp
> -
检查rownum的几个方法，我挪到 ObLogicalOperator 中了，原因如下：
1. 从功能上讲，这些方法不应该从属于 ObStaticEngineCG。这几个函数都是静态函数，可见他们的实现和ObStaticEngineCG的对象也没有啥关系
2. 在逻辑计划的travese阶段，插入物化算子前也需要检查rownum，在ObLogicalOperator中调用ObStaticEngineCG::find_rownum_expr(found, this)感觉很奇怪

2023-07-03 02:12 UTC, raywill commented on src/sql/code_generator/ob_static_engine_cg.cpp
> +          OZ(op->get_child(i)->find_rownum_expr(has_rownum_expr));
Good！

2023-07-03 03:38 UTC, raywill requested changes
请分别按照 review 修改。特别注意：
1. 一些成员，不是那么明显的，添加适当注释
2. 错误码覆盖问题
3. push_back 等函数调用的错误码返回值检查问题。如果确认不需要检查，那么就应该返回void，或者在调用处这么写： (void) func();

2023-07-03 03:38 UTC, raywill commented on src/sql/optimizer/ob_logical_operator.cpp
> +int ObLogicalOperator::alloc_op_pre(AllocOpContext& ctx)
在这个函数头顶上加一行注释，说明下吧：
// disable material op allocation in following cases:
// rownum, nlj, subplan filter, remote execution.

2023-07-03 03:38 UTC, raywill commented on src/sql/optimizer/ob_logical_operator.cpp
> +  if (get_plan()->get_optimizer_context().get_exec_ctx()->get_sql_ctx()->is_remote_sql_
这个和上面是 else if 关系还是，还是分段判断关系？这个 if 里面，有可能覆盖上面的错误码。

错误码覆盖，是非常大的坑。可能会导致一些线上非常难排查的问题。

2023-07-03 03:41 UTC, zhangyuqin1998 commented on src/sql/optimizer/ob_log_plan.cpp
> +                                        OPERATOR_NUMBERING,
> 做两次 OPERATOR_NUMBERING？为什么？必要性是？原来为什么不需要？

因为白名单和枚举的插入级别需要根据原始op id判断是否插入算子，所以需要先OPERATOR_NUMBERING分配原始的op id。插入物化算子后，再做一次OPERATOR_NUMBERING生成新的op id。
我后面在代码里加下注释解释这个事情～

2023-07-03 04:23 UTC, zhangyuqin1998 commented on src/sql/optimizer/ob_logical_operator.cpp
> +  if (get_plan()->get_optimizer_context().get_exec_ctx()->get_sql_ctx()->is_remote_sql_
> 这个和上面是 else if 关系还是，还是分段判断关系？这个 if 里面，有可能覆盖上面的错误码。
> 
> 错误码覆盖，是非常大的坑。可能会导致一些线上非常难排查的问题。

是分段关系，我处理一下错误码的问题

2023-07-03 05:55 UTC, zhangyuqin1998 commented on src/sql/resolver/dml/ob_dml_resolver.cpp
> +        if (0 == alloc_level.case_compare("all") || 0 == alloc_level.case_compare("ALL")) {
> 为什么不用 case 不敏感的 compare 函数？

这里是我搞错了，case_compare本身就是大小写不敏感，已经修改～

2023-07-03 05:56 UTC, zhangyuqin1998 commented on src/sql/resolver/dml/ob_dml_resolver.cpp
> +    if (OB_FAIL(alloc_op_hints.push_back(alloc_op_hint))) {
> 新手写 OB 代码最常犯的一个错误：错误码覆盖。假如上面的分支抛出了一个错误（L13599)，这里 OB_FAIL 宏会覆盖这个错误。

好滴，我把其他地方也检查一遍～

2023-07-04 01:32 UTC, zhangyuqin1998 commented on src/sql/resolver/dml/ob_hint.cpp
> +int ObGlobalHint::merge_alloc_op_hints(const ObIArray<ObAllocOpHint> &alloc_op_hints)
> 这个 merge 功能确认有相关 case 完整覆盖。

已经添加～

2023-07-04 02:02 UTC, zhangyuqin1998 commented on src/sql/ob_sql_define.h
> +#define IS_DUMMY_PHY_OPERATOR(op_type) ((op_type == PHY_MONITORING_DUMP || op_type == PHY_MATERIAL))
> 这个地方会不会有点危险？ PHY_MATERIAL 并不总是 DUMMY 算子，有些时候是实际有用的常规算子。
> 
> `int ObOperator::get_real_child(ObOperator *&child, const int32_t child_idx)` 请确认下这里是否安全。

确实是这样，这里我先改回去了

2023-07-04 02:04 UTC, zhangyuqin1998 commented on src/sql/resolver/dml/ob_hint.h
> +  int64_t tgt_id_;
tgt是target的缩写，已经添加注释

2023-07-04 02:51 UTC, zhangyuqin1998 commented on src/sql/optimizer/ob_logical_operator.cpp
> +    op_ids = visited_map_.get(op_type);
> 如果 get 失败呢？加防御报错。

这里get返回的不是错误码，是元素的指针，后面加了判空的防御逻辑～

2023-07-04 05:59 UTC, raywill commented on src/sql/resolver/dml/ob_hint.cpp
> +      if (OB_FAIL(BUF_PRINTF(")"))) {
错误码覆盖

2023-07-04 05:59 UTC, raywill commented on src/sql/optimizer/ob_logical_operator.cpp
> +  if (NULL == op_ids) {
上面如果发生了错误（L231），那么这里就可能是 NULL。原始错误码会被 OB_ERR_UNEXPECTED 覆盖。

2023-07-04 05:59 UTC, raywill commented on src/sql/optimizer/ob_logical_operator.cpp
> +    for (auto i = 0; !found && i < expr->get_param_count(); i++) {
这里，不同循环次数之间也可能发生错误码覆盖？

2023-07-04 05:59 UTC, raywill commented on src/sql/optimizer/ob_logical_operator.cpp
> +      for (int64_t i = 0; i < cur_path.count(); ++i) {
错误码覆盖？

2023-07-04 05:59 UTC, raywill commented on src/sql/optimizer/ob_logical_operator.cpp
> +      if (OB_FAIL(get_child(second_child)->recursively_disable_alloc_op_above(ctx))) {
覆盖了 5453 行的错误码。

2023-07-04 05:59 UTC, raywill commented on src/sql/optimizer/ob_logical_operator.cpp
> +  int ret = OB_SUCCESS;
加注释，说明下列情况是做什么，处理什么场景

2023-07-04 06:10 UTC, zhangyuqin1998 commented on src/sql/optimizer/ob_logical_operator.cpp
> +  if (NULL == op_ids) {
> 上面如果发生了错误（L231），那么这里就可能是 NULL。原始错误码会被 OB_ERR_UNEXPECTED 覆盖。

已经修改～

2023-07-04 06:17 UTC, zhangyuqin1998 commented on src/sql/optimizer/ob_logical_operator.cpp
> +  int ret = OB_SUCCESS;
done

2023-07-04 06:26 UTC, zhangyuqin1998 commented on src/sql/resolver/dml/ob_hint.cpp
> +      if (OB_FAIL(BUF_PRINTF(")"))) {
> 错误码覆盖

done

2023-07-04 07:48 UTC, zhangyuqin1998 commented on src/sql/optimizer/ob_logical_operator.cpp
> +    op_ids->push_back(op_id);
donw

2023-07-04 07:48 UTC, zhangyuqin1998 commented on src/sql/optimizer/ob_logical_operator.cpp
> +  cur_path.push_back(op_id_);
done

2023-07-04 07:48 UTC, zhangyuqin1998 commented on src/sql/optimizer/ob_logical_operator.cpp
> +  find_rownum_expr(found);
done

2023-07-04 07:48 UTC, zhangyuqin1998 commented on src/sql/optimizer/ob_logical_operator.cpp
> +    for (auto i = 0; !found && i < expr->get_param_count(); i++) {
done

2023-07-04 07:48 UTC, zhangyuqin1998 commented on src/sql/optimizer/ob_logical_operator.cpp
> +      for (int64_t i = 0; i < cur_path.count(); ++i) {
done

2023-07-04 07:48 UTC, zhangyuqin1998 commented on src/sql/optimizer/ob_logical_operator.cpp
> +      if (OB_FAIL(get_child(second_child)->recursively_disable_alloc_op_above(ctx))) {
done

2023-07-04 09:56 UTC, raywill approved these changes

2024-05-10 08:07 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/oceanbase/oceanbase?pullRequest=1437) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/oceanbase/oceanbase?pullRequest=1437) before we can accept your contribution.<br/><hr/>**zhangyuqin1998** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/oceanbase/oceanbase?pullRequest=1437) it.</sub>

2026-04-11 12:46 UTC, closed without merging