Add support for the IVFPQ vector index algorithm
oceanbase/oceanbase pull request #2041
Opened 2024-07-07 19:20 UTC by HollowMan6

Not ready at all, just want to get the CI test result while developing.

### Task Description

### Solution Description

### Passed Regressions

### Upgrade Compatibility

### Other Information

### Release Note

2024-08-12 02:54 UTC, a1iive commented
文档麻烦也提到pr里

2024-08-12 08:25 UTC, HollowMan6 commented
> 麻烦先把设计文档也提到pr里看下

给IVFPQ整合到了原版设计文档里，提交到了docs/vector-design-docs.md

2024-08-13 06:49 UTC, a1iive commented on src/share/vector_index/ob_tenant_pq_center_cache.cpp
> +int ObTenantPQCenterCache::convert_to_pq_index_vec(
这个过程看起来很麻烦，有没有可能直接在索引表增加原始向量列

2024-08-13 06:49 UTC, a1iive commented on src/sql/das/ob_das_scan_op.cpp
> +int ObIvfpqAnnScanOp::do_get_row(bool in_batch)
如果索引表里有原始向量列，是不是不用这么复杂的逻辑。这段逻辑感觉比增加一次回表操作还慢

2024-08-13 07:10 UTC, HollowMan6 commented on src/sql/das/ob_das_scan_op.cpp
> +int ObIvfpqAnnScanOp::do_get_row(bool in_batch)
这里只有当使用***分区***ANN查询才需要访问原始向量，当然可以在索引表存放原始向量列，主要问题是，如果直接在索引表增加原始向量列的话，IVFPQ节省存储空间的优势就完全没有体现了。并且目前也只有使用***分区***ANN查询计划才需要原始向量（因为目前在多个子分区获取到TOP-N，为了便于在DFO2中进行merge sort操作，需要将各个DFO内并行任务的结果根据向量距离整合为一个升序结果集）。我目前想不到有没有更好的方法解决这个问题，但是我感觉如果是仅仅为了方便当前***分区***ANN查询牺牲掉整体的节省存储空间优势的话有些可惜。

2024-08-13 07:11 UTC, HollowMan6 commented on src/share/vector_index/ob_tenant_pq_center_cache.cpp
> +int ObTenantPQCenterCache::convert_to_pq_index_vec(
convert_to_pq_index_vec这里不需要访问原始向量列，这里只是将索引建立完成后新插入/删除的向量根据已有数据转换成PQ量化后的压缩向量

2024-08-13 07:26 UTC, a1iive commented on src/share/vector_index/ob_tenant_pq_center_cache.cpp
> +int ObTenantPQCenterCache::convert_to_pq_index_vec(
了解了，这个函数太长了，把填cache那部分拆一下

2024-08-13 07:29 UTC, a1iive commented on src/sql/das/ob_das_scan_op.cpp
> +int ObIvfpqAnnScanOp::do_get_row(bool in_batch)
ob有压缩，相比查询的损失，存储空间不见得会很差，这两者的trade-off倒是可以实验一下看看。
现在有索引列的查询是回表么，如果是回表的话为什么多分区依赖原始向量

2024-08-13 07:55 UTC, HollowMan6 commented on src/sql/das/ob_das_scan_op.cpp
> +int ObIvfpqAnnScanOp::do_get_row(bool in_batch)
> 现在有索引列的查询是回表么，如果是回表的话为什么多分区依赖原始向量

目前分区ANN查询的时候似乎没有对每个分区进行回表操作，因为如果不加这步的话会报错（见https://ce-farm.oceanbase-dev.com/farm2/ci/?id=3906 mysqltest_4）。非分区ANN查询的时候应该是回表了，SELECT * 的时候直接输出的就是原始向量。

所以如果不加这步的话DFO2获取的是PQ量化之后的压缩向量
https://github.com/HollowMan6/oceanbase/blob/vector_search_update/docs/images/partition.png 一个更好的解决方案可能是分区ANN查询的时候对IVFPQ每个分区的index扫描也增加一下回表操作，但是目前还没搞清楚怎么添加

2024-08-13 08:02 UTC, a1iive commented on src/sql/das/ob_das_scan_op.cpp
> +int ObIvfpqAnnScanOp::do_get_row(bool in_batch)
我理解多分区table scan的时候也是可以回表的，你可以再看下

2024-08-13 14:10 UTC, HollowMan6 commented on src/share/vector_index/ob_ivf_index_search_helper.cpp
> +    if (centers_array_.count() <= center_idx && OB_FAIL(centers_array_.prepare_allocate(center_idx + 1))) {
这里主要是因为不知道center_idx最大值是多少，所以做一个判断，当不够的话allocate到当前的center_idx值，不知道这里有没有best practice处理这类问题

2024-08-13 14:17 UTC, HollowMan6 commented on src/share/vector_index/ob_ivfpq_index_build_helper.cpp
> +              } else if (OB_FAIL(ObTypeVector::alloc_and_copy_vector(allocator_, *center_helper_.get_center_vectors().at(nearest_center_idx), new_vector))) {
这里我觉得应该是需要的，alloc出来的内存用于保存计算出来的残差

2024-08-13 19:07 UTC, HollowMan6 commented on src/share/ob_index_builder_util.cpp
> +          accuracy.set_length(accuracy.get_length() / arg.vector_pq_seg_);
其实整除这块问题原本是打算，如果遇到不能整除的情况的话，用一个旋转向量解决的（raft库采用了这个方案https://docs.rapids.ai/api/raft/nightly/pylibraft_api/neighbors/#ivf-pq）但是目前注意到很多数据库的实现，包括milvus，都没有采用这个方案 https://milvus.io/docs/index.md?tab=floating （直接要求整除），所以现在计划给旋转向量功能在初始版本稳定之后，探究一下其对数据库场景下的性能影响，再决定是否添加。

目前暂时已添加整除防御。

2024-08-15 02:40 UTC, a1iive commented
> Hi @a1iive ! 感谢review，目前除了有疑问的点，其他都已经解决了，如果还有其他意见欢迎继续指正！后面我会继续看看怎么给分区的index扫描增加回表操作。
> 
> ~关于项目，我感觉另外还有一个可能可以修改的点是，因为pq量化后存储的向量每个数值都是int型的，而目前向量类型都统一划归为固定位数的float然后转varchar存储，我在想，可能在insert语句中增加int型向量的支持，判断如果向量内数值是int型 直接给末尾多余的零去除，转换为varchar存储的时候能节省很多空间，不知道您有对此有什么comment？如果觉得有价值的话后面我也研究研究看看~
> 
> **_研究了一下，之前理解有误，vector类型是通过float强制类型转换而非输出为可读字符串再解析的形式，所以即使使用int32，同样都占用32位，并不能节省空间。_**
> 
> Hi @a1iive! Thanks for the review. Except for the doubtful points, everything else has been resolved. If you have any other comments, please continue to correct me! Later I will continue to look at how to add table back operations to the index scan of the partition.
> 
> ~~ Regarding the project, I feel that another point that may be modified is that each value of the vector stored after pq quantization is int type, and currently the vector types are uniformly classified as fixed-digit float and then converted For varchar storage, I am thinking that we might add support for int type vectors in the insert statement. If the value in the vector is of int type, we can directly remove the extra zeros at the end. This can save a lot of space when converting to varchar storage. I wonder if you have any Any comments on this? If you think it’s valuable, I’ll do some research later~~
> 
> **_I did some research and found that I had a misunderstanding before. The vector type is cast through float type conversion rather than outputting it as a readable string and then parsing it. Therefore, even if int32 is used, it still occupies 32 bits and cannot save space. _**

好的，最近有别的事，晚些时候我再看下

2024-08-15 08:06 UTC, HollowMan6 commented on src/sql/das/ob_das_scan_op.cpp
> +int ObIvfpqAnnScanOp::do_get_row(bool in_batch)
尝试了一下，如果强制ivfpq查询的时候回表，会报output column does not exist in access column ids，后面研究研究为什么会导致这种情况：
![QQ_1723709055110](https://github.com/user-attachments/assets/2e94cef2-e6b0-4a8c-8504-2578851b79f6)

```bash
[2024-08-15 10:00:13.569633] INFO  [SQL.OPT] project_pruning_pre (ob_logical_operator.cpp:3557) [22135][T1_L0_G0][T1][Y27117F000001-00061FB43202B737-0-0] [lt=6] enforce index back for ivfpq(table_scan->get_table_id()=18446744073709551614, table_scan->get_table_type()=3)
[2024-08-15 10:00:13.569914] INFO  [SQL.CG] extract_das_access_exprs (ob_tsc_cg_service.cpp:723) [22135][T1_L0_G0][T1][Y27117F000001-00061FB43202B737-0-0] [lt=7] generate ivf index scan access exprs(scan_table_id=500724, op.get_container_table_id()=500725, op.get_real_index_table_id()=500724, op.get_extra_access_exprs()=[{item_type:"T_REF_COLUMN", result_type:{meta:{type:"BIGINT", collation:"binary", coercibility:"NUMERIC"}, accuracy:{length:-1, precision:-1, scale:-1}, flag:16386, calc_type:{type:"NULL", collation:"invalid_type", coercibility:"INVALID"}}, expr_info:["IS_COLUMN", "CNT_COLUMN"], rel_id:[1], table_id:18446744073709551614, column_id:19, database_name:"vector_test", table_name:"t1", synonym_name:"", synonym_db_name:"", column_name:"center_idx", column_flags:0, enum_set_values:[], is_lob_column:false, is_joined_dup_column:false, is_unpivot_mocked_column:false, is_hidden:false, from_alias_table:false, is_rowkey_column:true, is_unique_key_column:false, is_mul_key_column:false, is_strict_json_column:0, srs_id:18446744073709551584, udt_set_id:0}, {item_type:"T_REF_COLUMN", result_type:{meta:{type:"VECTOR", collation:"binary", coercibility:"NUMERIC"}, accuracy:{length:3, precision:-1, scale:-1}, flag:0, calc_type:{type:"NULL", collation:"invalid_type", coercibility:"INVALID"}}, expr_info:["IS_COLUMN", "CNT_COLUMN"], rel_id:[1], table_id:18446744073709551614, column_id:17, database_name:"vector_test", table_name:"t1", synonym_name:"", synonym_db_name:"", column_name:"v1", column_flags:0, enum_set_values:[], is_lob_column:false, is_joined_dup_column:false, is_unpivot_mocked_column:false, is_hidden:false, from_alias_table:false, is_rowkey_column:false, is_unique_key_column:false, is_mul_key_column:true, is_strict_json_column:0, srs_id:18446744073709551584, udt_set_id:0}])
[2024-08-15 10:00:13.570002] WDIAG [SQL.CG] generate_das_result_output (ob_tsc_cg_service.cpp:400) [22135][T1_L0_G0][T1][Y27117F000001-00061FB43202B737-0-0] [lt=30][errcode=-4016] output column does not exist in access column ids(ret=-4016, scan_ctdef.access_column_ids_=[cnt:2, 19, 17], output_cids.at(i)=16, output_cids=[16, 18], scan_ctdef.ref_table_id_=500724, scan_ctdef.ref_table_id_=500724)
[2024-08-15 10:00:13.570012] WDIAG [SQL.CG] generate_table_param (ob_tsc_cg_service.cpp:312) [22135][T1_L0_G0][T1][Y27117F000001-00061FB43202B737-0-0] [lt=10][errcode=-4016] failed to init result outputs(ret=-4016)
[2024-08-15 10:00:13.570018] WDIAG [SQL.CG] generate_das_scan_ctdef (ob_tsc_cg_service.cpp:1062) [22135][T1_L0_G0][T1][Y27117F000001-00061FB43202B737-0-0] [lt=4][errcode=-4016] generate table param failed(ret=-4016)
[2024-08-15 10:00:13.570021] WDIAG [SQL.CG] generate_tsc_ctdef (ob_tsc_cg_service.cpp:95) [22135][T1_L0_G0][T1][Y27117F000001-00061FB43202B737-0-0] [lt=2][errcode=-4016] generate das scan ctdef failed(ret=-4016, scan_ctdef.ref_table_id_=500724)
[2024-08-15 10:00:13.570025] WDIAG [SQL.ENG] generate_normal_tsc (ob_static_engine_cg.cpp:4830) [22135][T1_L0_G0][T1][Y27117F000001-00061FB43202B737-0-0] [lt=3][errcode=-4016] generate tsc ctdef failed(ret=-4016)
[2024-08-15 10:00:13.570029] WDIAG [SQL.ENG] generate_spec (ob_static_engine_cg.cpp:4234) [22135][T1_L0_G0][T1][Y27117F000001-00061FB43202B737-0-0] [lt=2][errcode=-4016] fail to exec generate_normal_tsc(op, spec)(ret=-4016)
[2024-08-15 10:00:13.570039] WDIAG [SQL.ENG] generate (ob_operator_factory.cpp:347) [22135][T1_L0_G0][T1][Y27117F000001-00061FB43202B737-0-0] [lt=4][errcode=-4016] generate operator specification failed(ret=-4016, log_op.get_name()="TABLE FULL SCAN", ob_phy_operator_type_str(spec.type_)="PHY_TABLE_SCAN")
[2024-08-15 10:00:13.570045] WDIAG [SQL.ENG] generate_spec (ob_operator_factory.cpp:459) [22135][T1_L0_G0][T1][Y27117F000001-00061FB43202B737-0-0] [lt=5][errcode=-4016] generate operator spec failed(type=3, ret=-4016)
[2024-08-15 10:00:13.570048] WDIAG [SQL.ENG] postorder_generate_op (ob_static_engine_cg.cpp:321) [22135][T1_L0_G0][T1][Y27117F000001-00061FB43202B737-0-0] [lt=3][errcode=-4016] generate operator spec failed(ret=-4016, phy_plan_=0x71ec7d0da050, ob_phy_operator_type_str(type)="PHY_TABLE_SCAN")
[2024-08-15 10:00:13.570054] WDIAG [SQL.ENG] postorder_generate_op (ob_static_engine_cg.cpp:256) [22135][T1_L0_G0][T1][Y27117F000001-00061FB43202B737-0-0] [lt=3][errcode=-4016] generate child op failed(ret=-4016, op.get_name()="PX PARTITION ITERATOR")
[2024-08-15 10:00:13.570059] WDIAG [SQL.ENG] postorder_generate_op (ob_static_engine_cg.cpp:256) [22135][T1_L0_G0][T1][Y27117F000001-00061FB43202B737-0-0] [lt=3][errcode=-4016] generate child op failed(ret=-4016, op.get_name()="TOP-N SORT")
[2024-08-15 10:00:13.570062] WDIAG [SQL.ENG] postorder_generate_op (ob_static_engine_cg.cpp:256) [22135][T1_L0_G0][T1][Y27117F000001-00061FB43202B737-0-0] [lt=2][errcode=-4016] generate child op failed(ret=-4016, op.get_name()="EXCHANGE OUT")
[2024-08-15 10:00:13.570065] WDIAG [SQL.ENG] postorder_generate_op (ob_static_engine_cg.cpp:256) [22135][T1_L0_G0][T1][Y27117F000001-00061FB43202B737-0-0] [lt=2][errcode=-4016] generate child op failed(ret=-4016, op.get_name()="PX COORDINATOR MERGE SORT")
[2024-08-15 10:00:13.570068] WDIAG [SQL.ENG] postorder_generate_op (ob_static_engine_cg.cpp:256) [22135][T1_L0_G0][T1][Y27117F000001-00061FB43202B737-0-0] [lt=2][errcode=-4016] generate child op failed(ret=-4016, op.get_name()="LIMIT")
[2024-08-15 10:00:13.570071] WDIAG [SQL.ENG] generate (ob_static_engine_cg.cpp:206) [22135][T1_L0_G0][T1][Y27117F000001-00061FB43202B737-0-0] [lt=2][errcode=-4016] failed to generate plan(ret=-4016)
[2024-08-15 10:00:13.570074] WDIAG [SQL.CG] generate_operators (ob_code_generator.cpp:86) [22135][T1_L0_G0][T1][Y27117F000001-00061FB43202B737-0-0] [lt=2][errcode=-4016] fail to code generate(ret=-4016)
[2024-08-15 10:00:13.570078] WDIAG [SQL.CG] generate (ob_code_generator.cpp:41) [22135][T1_L0_G0][T1][Y27117F000001-00061FB43202B737-0-0] [lt=2][errcode=-4016] fail to generate plan(ret=-4016)
[2024-08-15 10:00:13.570083] WDIAG [SQL] code_generate (ob_sql.cpp:3605) [22135][T1_L0_G0][T1][Y27117F000001-00061FB43202B737-0-0] [lt=4][errcode=-4016] Failed to generate physical plan(logical_plan=, ret=-4016)
[2024-08-15 10:00:13.570088] WDIAG [SQL] generate_plan (ob_sql.cpp:3201) [22135][T1_L0_G0][T1][Y27117F000001-00061FB43202B737-0-0] [lt=3][errcode=-4016] Failed to genenrate phy plan(ret=-4016)
[2024-08-15 10:00:13.570105] WDIAG [SQL] generate_physical_plan (ob_sql.cpp:2995) [22135][T1_L0_G0][T1][Y27117F000001-00061FB43202B737-0-0] [lt=4][errcode=-4016] failed to generate plan(ret=-4016)
[2024-08-15 10:00:13.570113] WDIAG [SQL] handle_physical_plan (ob_sql.cpp:4811) [22135][T1_L0_G0][T1][Y27117F000001-00061FB43202B737-0-0] [lt=4][errcode=-4016] Failed to generate plan(ret=-4016, result.get_exec_context().need_disconnect()=false)
[2024-08-15 10:00:13.570119] WDIAG [SQL] handle_text_query (ob_sql.cpp:2560) [22135][T1_L0_G0][T1][Y27117F000001-00061FB43202B737-0-0] [lt=5][errcode=-4016] fail to handle physical plan(ret=-4016)
```

2024-08-20 18:50 UTC, HollowMan6 commented on src/sql/das/ob_das_scan_op.cpp
> +int ObIvfpqAnnScanOp::do_get_row(bool in_batch)
尝试绕过上面的错误，进一步看了一下，发现似乎在对每个分区index扫描之后并不会立刻对每个分区的结果进行回表，而是统一起来对最终结果进行回表

2024-08-27 03:50 UTC, a1iive commented on src/sql/das/ob_das_scan_op.cpp
> +int ObIvfpqAnnScanOp::do_get_row(bool in_batch)
统一回表会有什么问题吗，我理解回表的话索引这里吐出rowkey列就可以，流程上是有什么卡点吗

2024-08-27 10:28 UTC, HollowMan6 commented on src/rootserver/ddl_task/ob_index_build_task.cpp
> +  } else if (ObIndexUsingType::USING_IVFFLAT == vector_index_using_type_ ||
这里本身ObIndexSSTableBuildTask类没有public方法来进行类型判断，所以这里没改，不过要添加一个private方法统一起来也可以

2024-08-27 10:35 UTC, HollowMan6 commented on src/share/vector_index/ob_ivfpq_index_search_helper.cpp
> +  } else if (OB_FAIL(new_vector->subtract(vector))) {
这里是残差的计算，谁减谁本身应该不影响最后的结果（只要和当时计算聚类中心的时候一致就好），不过如果一定要要求是qvector-center的话也可以改过来

2024-08-27 10:36 UTC, HollowMan6 commented on src/share/vector_index/ob_ivfpq_index_build_helper.cpp
> +  } else if (OB_FAIL(new_vector->subtract(vector))) {
同上，这里是残差的计算，谁减谁本身应该不影响最后的结果（只要和查询的时候算法一致就好），不过如果一定要要求是vector-center的话也可以改过来

2024-08-27 10:43 UTC, HollowMan6 commented on src/sql/das/ob_das_scan_op.cpp
> +int ObIvfpqAnnScanOp::do_get_row(bool in_batch)
![](https://github.com/HollowMan6/oceanbase/blob/vector_search_update/docs/images/partition.png)

我们需要最迟在DFO1时候结束的时候，对每个分区进行回表，获取到每个分区的原始向量。而一旦迟于这个时刻/不是对每个分区回表的话，就无法进行merge sort了，因为每个分区使用的是不同的聚类结果，而且无法直接对PQ量化后的向量进行merge sort。

2024-08-27 11:03 UTC, HollowMan6 commented on src/share/vector_index/ob_ivf_index_search_helper.cpp
> +    if (centers_array_.count() <= center_idx && OB_FAIL(centers_array_.prepare_allocate(center_idx + 1))) {
> ObArray直接push_back会自动扩容

这里主要关注的点在于，没有办法保证我们会按顺序获取到center_idx，所以直接push_back的话centers_array_.at(center_idx)会出问题，所以这里才采用了prepare_allocate

> 另外这个centers_array_是必要的吗，为什么不能用center_cache呢，如果center_cache里没有，也是正好可以先填进去的

这个确实可能是后续的一个优化方向，我后续研究研究

2024-08-27 11:06 UTC, a1iive commented on src/sql/das/ob_das_scan_op.cpp
> +int ObIvfpqAnnScanOp::do_get_row(bool in_batch)
这个图里也是先回表再merge sort的吧，我看计划也是这样的

2024-08-27 11:16 UTC, HollowMan6 commented on src/sql/das/ob_das_scan_op.cpp
> +int ObIvfpqAnnScanOp::do_get_row(bool in_batch)
> 这个图里也是先回表再merge sort的吧

我不太清楚这块了，那有可能是我对错误的table_scan强行设置了set_index_back(true)?

> 尝试了一下，如果强制ivfpq查询的时候回表，会报output column does not exist in access column ids，后面研究研究为什么会导致这种情况： 

> 我看计划也是这样的

您是在哪块怎么设置在DFO 1的时候回表的？如果能够这样回表这个问题应该就能直接解决，这块就不需要了

2024-08-27 11:33 UTC, a1iive commented on src/sql/das/ob_das_scan_op.cpp
> +int ObIvfpqAnnScanOp::do_get_row(bool in_batch)
index_back最早是在ObJoinOrder::get_simple_index_info里设置的。
有回表的话cg的时候会创一个lookup_ctdef，das scan op里应该会有一个lookup迭代器的，这套框架我理解依然是可以用的

2024-08-27 11:33 UTC, a1iive commented on src/sql/das/ob_das_scan_op.cpp
> +int ObIvfpqAnnScanOp::do_get_row(bool in_batch)
你需要看下das scan是怎么处理回表场景的

2024-08-27 11:34 UTC, HollowMan6 commented on src/share/vector_index/ob_ivfpq_index_search_helper.cpp
> +      int64_t center_idx = centers_top_array_.at(i).center_idx_;
我之前作为优先选择，确实尝试过直接创建一个struct（PQHeapCenterItem），作为ObBinaryHeap的template参数，但是最终发现ObBinaryHeap不支持这些没有固定size的类型（ObTypeVector和ObArray），所以最后就直接全部分开搞了

2024-08-27 11:38 UTC, a1iive commented on src/share/vector_index/ob_ivfpq_index_search_helper.cpp
> +      int64_t center_idx = centers_top_array_.at(i).center_idx_;
我这里是说centers_top_array_这个，看起来和直接用center_heap_没什么区别

2024-08-27 11:44 UTC, HollowMan6 commented on src/share/vector_index/ob_ivfpq_index_search_helper.cpp
> +      int64_t center_idx = centers_top_array_.at(i).center_idx_;
啊，这块的话是依赖排序的，需要根据n_probe选出距离最短的center依次存到centers_top_array_：
![](https://github.com/user-attachments/assets/945f2de7-46c7-471c-9c41-847819263be6)

2024-08-27 13:00 UTC, a1iive commented on src/share/vector_index/ob_ivfpq_index_search_helper.cpp
> +      int64_t center_idx = centers_top_array_.at(i).center_idx_;
我理解你意思了，pq_centers_dis_array_是按聚簇中心距离顺序排列的是吧，这个顺序是哪里依赖的？

2024-08-27 18:51 UTC, HollowMan6 commented on src/share/vector_index/ob_ivf_index_search_helper.cpp
> +    if (centers_array_.count() <= center_idx && OB_FAIL(centers_array_.prepare_allocate(center_idx + 1))) {
研究了一下发现centers_array_确实完全没必要，直接用centers_就好，所以给centers_array_删除了

2024-08-27 20:50 UTC, HollowMan6 commented on src/sql/das/ob_das_scan_op.cpp
> +int ObIvfpqAnnScanOp::do_get_row(bool in_batch)
![Screenshot From 2024-08-27 23-25-51](https://github.com/user-attachments/assets/3652e862-847f-4ef1-a7d2-df9d214105eb)

试了一下直接在`ObJoinOrder::get_simple_index_info`里强制设置index_back，但是计划里显示仍然是没开启index_back，应该是后面这个值被其他逻辑改写了。然后研究了一下在回表场景，ObDASScanOp的result_是一个LookupOp，并且rowkey_iter_是一个ObIvfAnnScanOp，所以这套回表机制应该是没问题的。

所以可能在`ObLogicalOperator::project_pruning_pre()`里设置强制回表这个思路还是正确的，就是这里遇到了output column does not exist in access column ids，可能我们需要在`generate_das_result_output (ob_tsc_cg_service.cpp:400)`里正确设置好需要回表查询的column，不过到底怎样处理好这个机制，来处理ivfpq的该用途，目前还是不太明晰

https://github.com/oceanbase/oceanbase/pull/2041#discussion_r1718097845

2024-08-28 02:38 UTC, a1iive requested changes

2024-08-28 02:38 UTC, a1iive commented on src/share/vector_index/ob_ivfpq_index_search_helper.cpp
> +      int64_t center_idx = centers_top_array_.at(i).center_idx_;
这里为什么会依赖n_probe个聚簇中心的距离顺序？ 从查询流程来看，距离表如果就按heap里的顺序来存放有什么问题吗？我理解距离表只是一个映射关系吧

2024-08-28 06:05 UTC, HollowMan6 commented on src/share/vector_index/ob_ivfpq_index_search_helper.cpp
> +      int64_t center_idx = centers_top_array_.at(i).center_idx_;
> 从查询流程来看，距离表如果就按heap里的顺序来存放有什么问题吗？我理解距离表只是一个映射关系吧

我不太明白，距离表里只会存放n_probe个聚簇中心的距离，并不会存放所有的聚簇中心的距离，为和非要按heap里的顺序存放，而且如果这样我找不到更好的方法和centers_top_array里存放的对应起来

![image](https://github.com/user-attachments/assets/174b3ef7-6b23-4c5e-b903-492c3af1da5b)

2024-08-28 06:12 UTC, a1iive commented on src/share/vector_index/ob_ivfpq_index_search_helper.cpp
> +      int64_t center_idx = centers_top_array_.at(i).center_idx_;
center_heap的大小不就是n_probes吗，为什么距离表需要按聚簇中心的距离排序？

2024-08-28 06:19 UTC, HollowMan6 commented on src/share/vector_index/ob_ivfpq_index_search_helper.cpp
> +      int64_t center_idx = centers_top_array_.at(i).center_idx_;
> center_heap的大小不就是n_probes吗

啊，对，之前这块理解有误，我误以为center_heap会存放所有聚簇中心，现在看来centers_top_array确实完全没必要，我马上修改一下

2024-09-05 20:39 UTC, HollowMan6 commented on src/sql/das/ob_das_scan_op.cpp
> +int ObIvfpqAnnScanOp::do_get_row(bool in_batch)
对于https://github.com/oceanbase/oceanbase/pull/2041#discussion_r1718097845
进一步研究，看起来应该是由于`scan_ctdef.pd_expr_spec_.access_exprs_` `scan_ctdef.access_column_ids_` 缺失回表需要访问的列导致的

2024-09-06 22:32 UTC, HollowMan6 commented on src/sql/das/ob_das_scan_op.cpp
> +int ObIvfpqAnnScanOp::do_get_row(bool in_batch)
> 对于[#2041 (comment)](https://github.com/oceanbase/oceanbase/pull/2041#discussion_r1718097845) 进一步研究，看起来应该是由于`scan_ctdef.pd_expr_spec_.access_exprs_` `scan_ctdef.access_column_ids_` 缺失回表需要访问的列导致的

进一步发现似乎是这里的问题导致的https://github.com/oceanbase/oceanbase/compare/259c09219e1598ca8dc90abf4ef8e7916774dd22..ad2d86ca056ee2a475d12326234533347067b48b#diff-a7bc766bf8202a7cd898de9db8e7412b1f04f1fc290d69e61e8e52c73201f22dR676-R680

然而此问题解决之后另外还遇到了lookup tablet loc为空的问题，似乎在这里无法获取数据表的tablet

2024-09-29 10:16 UTC, HollowMan6 commented on src/sql/das/ob_das_scan_op.cpp
> +int ObIvfpqAnnScanOp::do_get_row(bool in_batch)
目前还是没有找到头绪，因为截止日期已经临近了，所以我暂时撤回这部分修改（46ca28ca07）后续如果还有机会我会再进一步看看。

2024-10-09 19:25 UTC, HollowMan6 commented
Hi @GITHUBear & @a1iive! 想问一下目前有没有给PR合并进vector_search分支的计划。因为目前已经开始科研，[将分区的index扫描复用回表而不是使用sql](https://github.com/oceanbase/oceanbase/pull/2041#discussion_r1714748078)这个问题没有太多时间研究了，如果还有其他review意见欢迎随时提出。组委会给出的PR合并截止时间是10月31日24:00 UTC+8，感谢🙏！

2024-10-10 02:39 UTC, a1iive commented
ann-benchmark下ivfflat和ivfpq的性能对比能贴到评论吗

2024-10-10 07:01 UTC, HollowMan6 commented
> ann-benchmark下ivfflat和ivfpq的性能对比能贴到评论吗

因为资源有限，只在GitHub Actions里做了benchmark，跑成功的运行结果见https://github.com/HollowMan6/ann-benchmarks/actions/runs/10435079233 Artifacts

2024-10-10 07:33 UTC, a1iive commented
> > ann-benchmark下ivfflat和ivfpq的性能对比能贴到评论吗
> 
> 因为资源有限，只在GitHub Actions里做了benchmark，跑成功的运行结果见https://github.com/HollowMan6/ann-benchmarks/actions/runs/10435079233 Artifacts

能对比的数据太少，这组测试集同list和probe下召回率和性能差距有这么大，正常么
![image](https://github.com/user-attachments/assets/b29488fe-3cbe-45a6-8600-f79c5c8572f0)
![image](https://github.com/user-attachments/assets/37989122-adfd-4a19-ad03-b48100dc881b)

![image](https://github.com/user-attachments/assets/d2b9a59b-9a3e-45a1-9795-076a45bbdc18)
![image](https://github.com/user-attachments/assets/135ae72b-25cc-47ce-8f7b-ca5c19841675)

能否自行测试至少[Fashion-MNIST](https://github.com/zalandoresearch/fashion-mnist)和[SIFT](http://corpus-texmex.irisa.fr/)数据集进行对比

2024-10-10 07:41 UTC, a1iive commented
> > ann-benchmark下ivfflat和ivfpq的性能对比能贴到评论吗
> 
> 因为资源有限，只在GitHub Actions里做了benchmark，跑成功的运行结果见https://github.com/HollowMan6/ann-benchmarks/actions/runs/10435079233 Artifacts

参考这个[提交](https://github.com/GITHUBear/ann-benchmarks/commit/58712f10a054149813bf57fa37e1be3f5f6ba034)修改ann-benchmark，然后自己部署ob，使用ann_benchmark的--local模式进行测试。理论上一个10G的租户完全足够跑[Fashion-MNIST](https://github.com/zalandoresearch/fashion-mnist)和[SIFT](http://corpus-texmex.irisa.fr/)数据集

2024-10-10 08:10 UTC, HollowMan6 commented
> 能对比的数据太少，这组测试集同list和probe下召回率和性能差距有这么大，正常么 ![image](https://private-user-images.githubusercontent.com/38487370/375271477-b29488fe-3cbe-45a6-8600-f79c5c8572f0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg1NDc4OTcsIm5iZiI6MTcyODU0NzU5NywicGF0aCI6Ii8zODQ4NzM3MC8zNzUyNzE0NzctYjI5NDg4ZmUtM2NiZS00NWE2LTg2MDAtZjc5YzVjODU3MmYwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDEwVDA4MDYzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQxOWE2NjZjMzMyNzJkZGQxNjg5ZjUwYThkZjM0YzNmMjlkZWNiNDMwZTFlMmQ2NzIzNDkyNWZjODQ4YTY5OGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.k5WofEe-OZY_U7XTqeLDoHmMMY9rumcf0Z8EZDbEjvI) ![image](https://private-user-images.githubusercontent.com/38487370/375271404-37989122-adfd-4a19-ad03-b48100dc881b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg1NDc4OTcsIm5iZiI6MTcyODU0NzU5NywicGF0aCI6Ii8zODQ4NzM3MC8zNzUyNzE0MDQtMzc5ODkxMjItYWRmZC00YTE5LWFkMDMtYjQ4MTAwZGM4ODFiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDEwVDA4MDYzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRmN2JlYTg1NzhmMTM5MjEwMjVjOWIzMjcwOWJhYmU4OTIwMDViMGRlNTY1ODliNmNkZjdlMmNiMzRlNGNlODEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.t80wTo1L1u5LGIGH5Irz_6x9chLnk8oIpuYh5TWTdyc)
> 
> ![image](https://private-user-images.githubusercontent.com/38487370/375271939-d2b9a59b-9a3e-45a1-9795-076a45bbdc18.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg1NDc4OTcsIm5iZiI6MTcyODU0NzU5NywicGF0aCI6Ii8zODQ4NzM3MC8zNzUyNzE5MzktZDJiOWE1OWItOWEzZS00NWExLTk3OTUtMDc2YTQ1YmJkYzE4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDEwVDA4MDYzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgzODZjNzY3YzY5YzFmZDU5NzMxOTRkMGZmODUwNWNmNDllNTk4MzIzYmEwNzYyNGJiZDUzMjZiYWIwYjAyYmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0._5JJUKuI04uZGavEkXAvoC4ZLNJLxaQk4na0NQrmFqU) ![image](https://private-user-images.githubusercontent.com/38487370/375271898-135ae72b-25cc-47ce-8f7b-ca5c19841675.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg1NDc4OTcsIm5iZiI6MTcyODU0NzU5NywicGF0aCI6Ii8zODQ4NzM3MC8zNzUyNzE4OTgtMTM1YWU3MmItMjVjYy00N2NlLThmN2ItY2E1YzE5ODQxNjc1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDEwVDA4MDYzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRmZDViMDNmNzlkM2M3OTM1ZWJhNTBlMWM0OWIyNzhjYmQ2M2M5OTQyNzM0OWY5NGUxOThlYmRlY2M3YWE5OWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.xeQWeXaEjIFJytl2L4ctflKmvz8t7tbzO4yWVv6j5W8)

这个可能是PQ分段数的参数没有调优导致的，我后面有时间看看

> 能否自行测试至少[Fashion-MNIST](https://github.com/zalandoresearch/fashion-mnist)和[SIFT](http://corpus-texmex.irisa.fr/)数据集进行对比

> 参考这个[提交](https://github.com/GITHUBear/ann-benchmarks/commit/58712f10a054149813bf57fa37e1be3f5f6ba034)修改ann-benchmark，然后自己部署ob，使用ann_benchmark的--local模式进行测试。理论上一个10G的租户完全足够跑[Fashion-MNIST](https://github.com/zalandoresearch/fashion-mnist)和[SIFT](http://corpus-texmex.irisa.fr/)数据集

OK, 之前我在我自己电脑上跑了一下，16G的内存，似乎不能跑起来，后面我如果还有时间的话再看看

2024-10-30 01:35 UTC, a1iive approved these changes
LGTM

2024-10-30 01:50 UTC, merged