Issue#2078: For LOAD DATA LOCAL, no error is reported when the file name is empty.
oceanbase/oceanbase pull request #2094
Opened 2024-08-15 04:57 UTC by ZhuKaley

Issue: #2078

2024-08-15 04:58 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/oceanbase/oceanbase?pullRequest=2094) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/oceanbase/oceanbase?pullRequest=2094) before we can accept your contribution.<br/><hr/>**zhuyangkai** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/oceanbase/oceanbase?pullRequest=2094) it.</sub>

2024-08-15 05:49 UTC, hnwyllmm requested changes

2024-08-15 05:49 UTC, hnwyllmm commented on src/sql/resolver/cmd/ob_load_data_resolver.cpp
> +    if (OB_UNLIKELY(file_name.empty()) && ObLoadFileLocation::CLIENT_DISK != load_args.load_file_storage_) {
应该是：
if (file_name.empty()) {
  if (ObLoadFileLocation::CLIENT_DISK != load_args.load_file_storage_) {
    ret = OB_FILE_NOT_EXIST;
  } else {
    // do nothing
  }
  ...
} else {
 ...
}
??

能否帮忙确认，JDBC+MySQL中，如果输入一个根本不存在的文件名，mysql也不会校验，比如 
load data local infile '123' into table t xxxx;

2024-08-15 06:33 UTC, ZhuKaley commented on src/sql/resolver/cmd/ob_load_data_resolver.cpp
> +    if (OB_UNLIKELY(file_name.empty()) && ObLoadFileLocation::CLIENT_DISK != load_args.load_file_storage_) {
1、我按你的修改方法重新提交一下；
2、输入一个根本不存在的文件名，MySQL没有检查，客户端在读文件时，发现文件不存在，会报文件不存在的错误。
报错信息如下：
Exception in thread "main" java.lang.RuntimeException: java.sql.SQLException: Unable to open file 'lllllll'for 'LOAD DATA LOCAL INFILE' command.Due to underlying IOException: 

** BEGIN NESTED EXCEPTION ** 

java.io.FileNotFoundException
MESSAGE: lllllll (No such file or directory)

STACKTRACE:

java.io.FileNotFoundException: lllllll (No such file or directory)
        at java.base/java.io.FileInputStream.open0(Native Method)
        at java.base/java.io.FileInputStream.open(FileInputStream.java:219)
        at java.base/java.io.FileInputStream.<init>(FileInputStream.java:157)
        at java.base/java.io.FileInputStream.<init>(FileInputStream.java:112)
        at com.mysql.cj.protocol.a.NativeProtocol.sendFileToServer(NativeProtocol.java:1757)
        at com.mysql.cj.protocol.a.TextResultsetReader.read(TextResultsetReader.java:107)
        at com.mysql.cj.protocol.a.TextResultsetReader.read(TextResultsetReader.java:48)
        at com.mysql.cj.protocol.a.NativeProtocol.read(NativeProtocol.java:1590)
        at com.mysql.cj.protocol.a.NativeProtocol.readAllResults(NativeProtocol.java:1644)
        at com.mysql.cj.protocol.a.NativeProtocol.sendQueryPacket(NativeProtocol.java:953)
        at com.mysql.cj.protocol.a.NativeProtocol.sendQueryString(NativeProtocol.java:886)
        at com.mysql.cj.NativeSession.execSQL(NativeSession.java:1073)
        at com.mysql.cj.jdbc.StatementImpl.executeInternal(StatementImpl.java:724)
        at com.mysql.cj.jdbc.StatementImpl.execute(StatementImpl.java:648)
        at Main.testMySQL(Main.java:79)
        at Main.main(Main.java:36)


** END NESTED EXCEPTION **


        at Main.testMySQL(Main.java:91)
        at Main.main(Main.java:36)
Caused by: java.sql.SQLException: Unable to open file 'lllllll'for 'LOAD DATA LOCAL INFILE' command.Due to underlying IOException: 

** BEGIN NESTED EXCEPTION ** 

java.io.FileNotFoundException
MESSAGE: lllllll (No such file or directory)

STACKTRACE:

java.io.FileNotFoundException: lllllll (No such file or directory)
        at java.base/java.io.FileInputStream.open0(Native Method)
        at java.base/java.io.FileInputStream.open(FileInputStream.java:219)
        at java.base/java.io.FileInputStream.<init>(FileInputStream.java:157)
        at java.base/java.io.FileInputStream.<init>(FileInputStream.java:112)
        at com.mysql.cj.protocol.a.NativeProtocol.sendFileToServer(NativeProtocol.java:1757)
        at com.mysql.cj.protocol.a.TextResultsetReader.read(TextResultsetReader.java:107)
        at com.mysql.cj.protocol.a.TextResultsetReader.read(TextResultsetReader.java:48)
        at com.mysql.cj.protocol.a.NativeProtocol.read(NativeProtocol.java:1590)
        at com.mysql.cj.protocol.a.NativeProtocol.readAllResults(NativeProtocol.java:1644)
        at com.mysql.cj.protocol.a.NativeProtocol.sendQueryPacket(NativeProtocol.java:953)
        at com.mysql.cj.protocol.a.NativeProtocol.sendQueryString(NativeProtocol.java:886)
        at com.mysql.cj.NativeSession.execSQL(NativeSession.java:1073)
        at com.mysql.cj.jdbc.StatementImpl.executeInternal(StatementImpl.java:724)
        at com.mysql.cj.jdbc.StatementImpl.execute(StatementImpl.java:648)
        at Main.testMySQL(Main.java:79)
        at Main.main(Main.java:36)


** END NESTED EXCEPTION **


        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:129)
        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97)
        at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
        at com.mysql.cj.jdbc.StatementImpl.executeInternal(StatementImpl.java:764)
        at com.mysql.cj.jdbc.StatementImpl.execute(StatementImpl.java:648)
        at Main.testMySQL(Main.java:79)
        ... 1 more

2024-08-15 06:51 UTC, ZhuKaley commented on src/sql/resolver/cmd/ob_load_data_resolver.cpp
> +    if (OB_UNLIKELY(file_name.empty()) && ObLoadFileLocation::CLIENT_DISK != load_args.load_file_storage_) {
已重新提交

2024-08-16 01:33 UTC, hnwyllmm commented on src/sql/resolver/cmd/ob_load_data_resolver.cpp
> +    if (OB_UNLIKELY(file_name.empty()) && ObLoadFileLocation::CLIENT_DISK != load_args.load_file_storage_) {
感谢。
你的测试结果非常重要。说明在MySQL中，load local模式不会去校验文件名是否合法的，都在MySQL客户端自己做校验。为了更好的兼容性，那LOCAL模式时应该这么操作是否应该这么调整：
原来的代码：
```cpp
ObString file_name(file_name_node->str_len_, file_name_node->str_value_);
    if (OB_UNLIKELY(file_name.empty())) {
```

应该修改为：
```cpp
ObString file_name(file_name_node->str_len_, file_name_node->str_value_);
if (ObLoadFileLocation::CLIENT_DISK == load_args.load_file_storage_) {
   // 处理LOCAL模式的文件，不关心文件名是否有问题
   if (OB_FAIL(load_args.file_iter_.add_files(file_name)) {
        LOG_WARN("failed to add file to file_iter", K(ret), K(file_name));
   }
} else if (OB_UNLIKELY(file_name.empty())) {
   // 这里处理SERVER和OSS模式下的文件
   .....
```

你看看是否合理

2024-08-21 07:36 UTC, hnwyllmm approved these changes

2024-08-22 02:23 UTC, merged