expr: implement UUID_TO_BIN, BIN_TO_UUID, IS_UUID
oceanbase/oceanbase pull request #616
Opened 2021-11-27 15:14 UTC by b41sh

### What changes were proposed in this pull request?

implement expression functions UUID_TO_BIN, BIN_TO_UUID, IS_UUID

### Why are the changes needed?

implement issue [#480](https://github.com/oceanbase/oceanbase/issues/480)

### Will break the compatibility? How if so?

no

### Does this PR introduce any user-facing change?
no

### How was this patch tested?

### Checklist

- [ ] I've run the tests to see all new and existing tests pass.
- [ ] If this Pull Request resolves an issue, I linked to the issue in the text above.
- [ ] I've informed the technical writer about the documentation change if necessary.

2021-11-28 00:55 UTC, b41sh commented
PTAL @hnwyllmm

2022-01-17 03:36 UTC, hnwyllmm requested changes
需要增加相关的单元测试和mysql test

2022-01-17 03:36 UTC, hnwyllmm commented on src/sql/engine/expr/ob_expr_uuid.cpp
> +int ObExprUuidToBin::hexchar_to_int(char c) {
大写字母也是合法的字符

2022-08-08 07:54 UTC, hnwyllmm commented
too long time to see feedback

2022-08-08 07:54 UTC, closed without merging