adding AVX512 sort feature during creating index
oceanbase/oceanbase pull request #887
Opened 2022-04-24 05:44 UTC by xtangxtang

### What changes were proposed in this pull request?
This change is to add avx512 sort during create Index. Before this change std::sort is used during creating index. Avx512 sort is intruduced by paper "A Novel Hybrid Quicksort Algorithm Vectorized using AVX-512 on Intel Skylake". 

### Why are the changes needed?
After adopting the change. creating index can speed up from 20% ~ 47% according to different index type. The performance workload is SSB. The table and creating index steps is as following SQL:
    create table lineitem (
    l_orderkey bigint not null,
    l_partkey bigint not null,
    l_suppkey bigint not null,
    l_linenumber bigint not null,
    l_quantity bigint not null,
    l_extendedprice bigint not null,
    l_discount bigint not null,
    l_tax bigint not null,
    l_returnflag char(1) default null,
    l_linestatus char(1) default null,
    l_shipdate date not null,
    l_commitdate date default null,
    l_receiptdate date default null,
    l_shipinstruct char(25) default null,
    l_shipmode char(10) default null,
    l_comment varchar(44) default null,
    primary key(l_orderkey, l_linenumber))
    tablegroup = tpch_tg_100g_lineitem_order_group
    partition by key (l_orderkey) partitions 192;
    
    create index I_L_ORDERKEY on lineitem(l_orderkey) local;
    create index I_L_SHIPINS on lineitem(l_shipinstruct) local;
    create index I_L_SHIPDATE_COMMITDATE on lineitem(l_shipdate, l_commitdate) local;
    
    drop index I_L_ORDERKEY on lineitem;
    drop index I_L_SHIPINS on lineitem;
    drop index I_L_SHIPDATE_COMMITDATE on lineitem;    

The performance is test on Intel(R) Xeon(R) Gold 6252 CPU @ 2.10GHz and the results is (unit is second):    

![image](https://user-images.githubusercontent.com/3771594/164957944-ff597d06-d55d-44e1-b1af-57a6a8bbb440.png)

### Will break the compatibility? How if so?

Because the AVX512 is only available on Intel CPU and even since Intel Skylake CPU can support AVX512.  Some condition is added to avoid breaking the compability:

* ENABLE_AVX512F is a new enviroment in build.sh, if it is open the OceanBase will compile the AVX512 code
* __builtin_cpu_supports("avx512f")：is  added in src/storage/ob_parallel_external_sort.h. It will runtime check if current CPU surpport AVX512.

So these two switcheds decide if the AVX512 sort is running. 

![image](https://user-images.githubusercontent.com/3771594/164958198-decf1a56-0830-445d-90a8-3665f8c80c0d.png)

### Does this PR introduce any user-facing change?
No

### How was this patch tested?
The patch currently is not performance the unit test.

### Checklist

- [X ] I've run the tests to see all new and existing tests pass.
- [X ] If this Pull Request resolves an issue, I linked to the issue in the text above.
- [X] I've informed the technical writer about the documentation change if necessary.

### Intruduction for this change
The attached PDF summary the changes for this path
[OSD_AVX512_Eanbling_README.MD at main · epeshared_OSD_AVX512_Eanbling.pdf](https://github.com/oceanbase/oceanbase/files/8549078/OSD_AVX512_Eanbling_README.MD.at.main.epeshared_OSD_AVX512_Eanbling.pdf)

2022-05-18 03:37 UTC, hnwyllmm commented on unittest/storage/test_parallel_external_sort.cpp
> +
这段代码是因为avx512比较是按照二进制比较的，所以需要加个函数get_sort_key来帮助将任意内型的key转换成可以按照二进制比较的key。因为TestItem里面的key都是int64的，所以可以直接通过内存拷贝将int64转成可以利用avx512比较的二进制形式。
对于加AVX宏开关，因为如果不走avx512分支的话，get_sort_key是不会被调用的，所以当avx没打开的话，这个函数是不会被调用的。但是也尅加上开个，这样编译的时候就不会编译这个函数的了。

2022-05-27 03:48 UTC, hnwyllmm approved these changes
LGTM

2022-05-27 03:48 UTC, hnwyllmm commented
/merge

2022-06-06 09:48 UTC, hnwyllmm commented on run/observer.pid
> +3514848
测试代码不需要提交上来。

2022-06-06 09:49 UTC, hnwyllmm commented on deps/oblib/src/common/object/ob_object.cpp
> +            bool is_valid_collation = false;
可以解析下这段代码吗？谢谢

2022-06-06 09:50 UTC, hnwyllmm commented on deps/oblib/src/common/object/ob_object.cpp
> +int ObObj::make_sort_key(char* to, int16_t& offset, int32_t& size,
需要增加此函数的单元测试

2022-06-06 09:51 UTC, hnwyllmm commented on deps/oblib/src/common/object/ob_object.cpp
> +    case ObUNumberType: {
类型少了一些，需要覆盖全量的，比如hexstring，text等等

2022-06-06 09:52 UTC, hnwyllmm commented on src/storage/ob_avx512_sort.h
> +class SortWithAvx512 {
整个算法的单测需要补下的。

2022-06-06 09:53 UTC, hnwyllmm requested changes
需要做些针对性的调整。

2022-06-27 10:08 UTC, xtangxtang commented on run/observer.pid
> +3514848
在新的commit中已经删除

2022-06-27 10:10 UTC, xtangxtang commented on deps/oblib/src/common/object/ob_object.cpp
> +int ObObj::make_sort_key(char* to, int16_t& offset, int32_t& size,
在新的commit
https://github.com/oceanbase/oceanbase/pull/887/commits/a1becfd40f6ad717ec390f20db9964f1db8df0a5
中对test_parallel_external_sort.cpp新增了UT test_avx512_sort_type

2022-06-27 10:15 UTC, xtangxtang commented on deps/oblib/src/common/object/ob_object.cpp
> +    case ObUNumberType: {
在新的commit中对make_sort_key做了如果遇到不支持的类型，将返回OB_NOT_SUPPORTED错误码，然后在ob_parallel_external_sort.h的finish函数和build_fragment函数中判断如果返回值是OB_NOT_SUPPORTED，将排序算法切换到以前的std::sort。

2022-06-30 00:53 UTC, xtangxtang commented on deps/oblib/src/common/object/ob_object.cpp
> +int ObObj::make_sort_key(char* to, int16_t& offset, int32_t& size,
是否需要对make_sort_key所有支持的type做验证？

2022-06-30 00:54 UTC, xtangxtang commented on src/storage/ob_avx512_sort.h
> +class SortWithAvx512 {
在https://github.com/oceanbase/oceanbase/pull/887/commits/1893e1ec369fa1f35f7e309ca759da8582757596
这个commit中加了SortWithAvx512.sort的UTcase

2022-07-08 03:01 UTC, xtangxtang commented on deps/oblib/src/common/object/ob_object.cpp
> +int ObObj::make_sort_key(char* to, int16_t& offset, int32_t& size,
在 https://github.com/oceanbase/oceanbase/pull/887/commits/d44db7097397558ffb108aeedd349cb112b70cf6 这个commit中新加了test_avx512_sort_type UT对全部ob type做了验证。

2022-07-08 03:02 UTC, xtangxtang commented on deps/oblib/src/common/object/ob_object.cpp
> +    case ObUNumberType: {
在 https://github.com/oceanbase/oceanbase/commit/d44db7097397558ffb108aeedd349cb112b70cf6 这个commit中新加了test_avx512_sort_type UT对全部ob type做了验证。

2022-07-08 03:02 UTC, xtangxtang commented on src/storage/ob_avx512_sort.h
> +class SortWithAvx512 {
在 https://github.com/oceanbase/oceanbase/commit/d44db7097397558ffb108aeedd349cb112b70cf6 这个commit中新加了test_avx512_sort_type UT对SortWithAvx512.sort做了验证

2022-07-12 02:09 UTC, xtangxtang commented on deps/oblib/src/common/object/ob_object.cpp
> +            bool is_valid_collation = false;
这段代码前面用t1表示在一个9个字节的数据块中的需要拷贝的起始位置，t2表示在一个9个字节的数据块中拷贝的结束位置。因为t1和t2之间可能会跨越多个数据块。所以需要用sortkey_start表示需要拷贝的起始数据位置，sortkey_end表示需要拷贝的结束数据位置。（(offset - 1) / 9 * 8表示需要拷贝的起始数据块，((offset - 1) + need) / 9 * 8表示需要拷贝的结束数据块位置）

2022-08-09 08:05 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/oceanbase/oceanbase?pullRequest=887) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/oceanbase/oceanbase?pullRequest=887) before we can accept your contribution.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: xtangxtang<br/>:x: ruclz<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/oceanbase/oceanbase?pullRequest=887) it.</sub>

2023-04-02 12:44 UTC, LINxiansheng commented
transfer #1325

2023-04-02 12:44 UTC, closed without merging